### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by schneidersoft** [MartinHelmut/cpp-gui-template-sdl2-opengl#8]
Guess I'm an idiot but... how to build it? I am on debian with SDL2 cmake gcc ninja-build and build-essentials installed.

I have tried ```cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -B build/debug``` in the root directory. This only hangs after the following output

```
-- The CXX compiler identification is GNU 12.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Ccache not found
-- Treat compiler warnings as errors
```

**Comment by MartinHelmut** [comment]
Hey, you're absolutely right on the _"how to build"_, as described in the [Quick Start guide](https://github.com/MartinHelmut/cpp-gui-template-sdl2-opengl/blob/main/docs/QuickStart.md), this would be the first command to run, to configure and build.

```shell
cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -B build/debug
cmake --build build/debug
```

I have no problems doing so at least on an Ubuntu 22.04 running zsh 🤔 Can you provide exact versions, for Debian, CMake, ninja-build, and so on? Also, what terminal environment you're using? Then I can set up a VM and try to replicate your issue.

**Comment by schneidersoft** [comment]
Hi Martin,
Turns out it isn't stuck... just downloading something. It takes a while, but then finally does build.

**Comment by MartinHelmut** [comment]
Ahh cool! In that case I'll close the issue. Thanks for coming back 🙌🏻
